# Nome do workflow que aparecerá nas opções de execução
name: "YFG - PGATS - TCD - DISC9 - CI Execução Manual -> Teste Web"

# Gatilho para execução manual
on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4 # Clonando o repositório

      - name: Instalando Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn install

      - name: Rodar Testes E2E
        run: yarn test # Comando para executar os testes

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./cypress/reports # mudado de playright para cypress
