# Nome do workflow que aparecerá nas opções de execução
name: "YFG - PGATS - TCD - DISC9 - CI Execução Manual -> Teste Web"

# Gatilho para execução manual
on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4 # Clonando o repositório

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Rodar Testes E2E
        run: yarn run e2e # Comando para executar seus testes

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./cypress/results # Altere para o caminho do seu relatório de testes, se necessário
